---
micronaut:
    application:
        name: preparedq

---
postgres:
    reactive:
        client:
            port: 5432
            host: localhost
            database: postgres
            user: postgres
            password: discoStuLovesDisco
            maxSize: 5